package organizacion.proyecto;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ClienteAPAP implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "edad")
   private java.lang.Integer edad;
   @org.kie.api.definition.type.Label(value = "salario")
   private java.lang.Integer salario;
   @org.kie.api.definition.type.Label(value = "credito")
   private java.lang.Integer credito;

   public ClienteAPAP()
   {
   }

   public java.lang.Integer getEdad()
   {
      return this.edad;
   }

   public void setEdad(java.lang.Integer edad)
   {
      this.edad = edad;
   }

   public java.lang.Integer getSalario()
   {
      return this.salario;
   }

   public void setSalario(java.lang.Integer salario)
   {
      this.salario = salario;
   }

   public java.lang.Integer getCredito()
   {
      return this.credito;
   }

   public void setCredito(java.lang.Integer credito)
   {
      this.credito = credito;
   }

   public ClienteAPAP(java.lang.Integer edad, java.lang.Integer salario,
         java.lang.Integer credito)
   {
      this.edad = edad;
      this.salario = salario;
      this.credito = credito;
   }

}